#! /usr/bin/python
# vim: set fileencoding=utf-8 :
# (c) 2011 Marcos Dione <mdione@grulic.org.ar>

# This file is part of satyr.

# satyr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.

# satyr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with satyr.  If not, see <http://www.gnu.org/licenses/>.

# dbus
import dbus
import dbus.mainloop.qt
import dbus.service

# std python
import sys

# local
from satyr.common import BUS_NAME
from satyr.backend import Backend
import satyr

def main ():
    app, args= satyr.createApp ()

    dbus.mainloop.qt.DBusQtMainLoop (set_as_default=True)
    bus= dbus.SessionBus ()
    busName= dbus.service.BusName (BUS_NAME, bus=bus)

    backend= Backend (app, args, busName=busName, busPath='/backend')

    return app.exec_ ()

if __name__=='__main__':
    sys.exit (main ())

# end
